'use client';

import { useState } from 'react';

interface Message {
  role: 'user' | 'assistant';
    content: string;
    }

    export default function EnterpriseChat() {
      const [messages, setMessages] = useState<Message[]>([]);
        const [input, setInput] = useState('');
          const [loading, setLoading] = useState(false);

            const tenantId = 'tenant-corp-alpha';
              const department = 'finance';

                const handleSendMessage = async (e: React.FormEvent) => {
                    e.preventDefault();
                        if (!input.trim() || loading) return;

                            const userMessage: Message = { role: 'user', content: input };
                                setMessages((prev) => [...prev, userMessage]);
                                    setInput('');
                                        setLoading(true);

                                            setMessages((prev) => [...prev, { role: 'assistant', content: '' }]);

                                                try {
                                                      const response = await fetch('/api/chat', {
                                                              method: 'POST',
                                                                      headers: { 'Content-Type': 'application/json' },
                                                                              body: JSON.stringify({ question: input, tenantId, department }),
                                                                                    });

                                                                                          if (!response.body) return;
                                                                                                const reader = response.body.getReader();
                                                                                                      const decoder = new TextDecoder();

                                                                                                            while (true) {
                                                                                                                    const { value, done } = await reader.read();
                                                                                                                            if (done) break;

                                                                                                                                    const textChunk = decoder.decode(value);
                                                                                                                                            setMessages((prev) => {
                                                                                                                                                      const updated = [...prev];
                                                                                                                                                                const lastMessage = updated[updated.length - 1];
                                                                                                                                                                          lastMessage.content += textChunk;
                                                                                                                                                                                    return updated;
                                                                                                                                                                                            });
                                                                                                                                                                                                  }
                                                                                                                                                                                                      } catch (err) {
                                                                                                                                                                                                            console.error('Failed to read live server token chunks', err);
                                                                                                                                                                                                                } finally {
                                                                                                                                                                                                                      setLoading(false);
                                                                                                                                                                                                                          }
                                                                                                                                                                                                                            };

                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                  <main className="flex flex-col h-screen max-h-screen bg-slate-950 text-slate-50 font-sans">
                                                                                                                                                                                                                                        <header className="p-4 border-b border-slate-800 bg-slate-900/50 backdrop-blur">
                                                                                                                                                                                                                                                <h1 className="text-lg font-bold tracking-tight text-emerald-400">Enterprise Core Engine</h1>
                                                                                                                                                                                                                                                        <p className="text-xs text-slate-400">Tenant: {tenantId} | Domain: {department}</p>
                                                                                                                                                                                                                                                              </header>

                                                                                                                                                                                                                                                                    <section className="flex-1 overflow-y-auto p-4 space-y-4">
                                                                                                                                                                                                                                                                            {messages.length === 0 && (
                                                                                                                                                                                                                                                                                      <div className="text-center text-slate-500 py-12 text-sm">
                                                                                                                                                                                                                                                                                                  Pipeline active. Ask a question to read isolated tenant storage states.
                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                            {messages.map((msg, index) => (
                                                                                                                                                                                                                                                                                                                                      <div key={index} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                                                                                                                                                                                                                                                                                                                                                  <div className={`max-w-[85%] rounded-xl p-3 text-sm leading-relaxed ${
                                                                                                                                                                                                                                                                                                                                                                msg.role === 'user' ? 'bg-emerald-600 text-white rounded-tr-none' : 'bg-slate-800 text-slate-100 rounded-tl-none'
                                                                                                                                                                                                                                                                                                                                                                            }`}>
                                                                                                                                                                                                                                                                                                                                                                                          {msg.content || (loading && index === messages.length - 1 ? 'Thinking...' : '')}
                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                              </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                    <form onSubmit={handleSendMessage} className="p-4 border-t border-slate-800 bg-slate-900/50">
                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              value={input}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={(e) => setInput(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      placeholder="Query your enterprise knowledge base..."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="flex-1 bg-slate-800 text-sm rounded-lg px-4 py-3 text-slate-100 placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-emerald-500"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="bg-emerald-500 hover:bg-emerald-600 disabled:bg-slate-700 text-slate-950 font-semibold px-5 rounded-lg text-sm transition-all"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Send
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }